# Generated by Django 3.1 on 2020-08-15 15:38

from django.db import migrations, models
import django_minio_backend.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=django_minio_backend.models.MinioBackend(bucket_name='django-backend-dev-public'), upload_to=django_minio_backend.models.iso_date_prefix)),
            ],
        ),
    ]
