# Generated by Django 5.1.4 on 2025-01-05 00:31

import DjangoExampleApplication.models
import DjangoExampleApplication.storages
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoExampleApplication', '0003_genericattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=DjangoExampleApplication.storages.get_public_storage, upload_to=django_minio_backend.models.iso_date_prefix),
        ),
        migrations.AlterField(
            model_name='privateattachment',
            name='file',
            field=models.FileField(storage=DjangoExampleApplication.storages.get_private_storage, upload_to=DjangoExampleApplication.models.PrivateAttachment.set_file_path_name, verbose_name='Object Upload'),
        ),
        migrations.AlterField(
            model_name='publicattachment',
            name='file',
            field=models.FileField(storage=DjangoExampleApplication.storages.get_public_storage, upload_to=django_minio_backend.models.iso_date_prefix, verbose_name='Object Upload'),
        ),
    ]
