# Generated by Django 5.2.8 on 2025-11-08 17:14

import DjangoExampleApplication.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoExampleApplication', '0004_alter_image_image_alter_privateattachment_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSystemAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='File System Attachment ID')),
                ('file', models.FileField(storage=DjangoExampleApplication.storages.get_filesystem_storage, upload_to='', verbose_name='Object Upload')),
            ],
        ),
    ]
