# Generated by Django 5.2.8 on 2025-11-09 16:54

import DjangoExampleApplication.storages
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoExampleApplication', '0005_filesystemattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=DjangoExampleApplication.storages.get_image_storage, upload_to=django_minio_backend.models.iso_date_prefix),
        ),
    ]
